### PR TITLE
Updated calendar dates (2024-25)

### PR DESCRIPTION
**Pull request by cunhapedro25**
Updated the dates for the new academic year and added a link to the school's official document.

image

### CODE REVIEW

**Comment by joaoalves03** [comment]
LGTM 👍 🚢 it

**Comment by cunhapedro25** [comment]
Ah forgot to say that "change date" is hard coded because uhmmmm yea :+1:

**Comment by rodrigosa7** [comment]
:shipit:

**Comment by mattcapazz** [comment]
LGTM 🛳️

**Pull request merged**
